[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Future of Work: How Artificial Intelligence Will Transform the Workplace and Create New Job Opportunities"
